# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0589306cc48bcfeca43f6b8c3040c20"
name = "BC Cannabis Extensions Test"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
